
package test.artefact.friends;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FriendWS2", targetNamespace = "http://webservices2/", wsdlLocation = "http://localhost:8080//PhasebookWSEJB/FriendWS2?wsdl")
public class FriendWS2_Service
    extends Service
{

    private final static URL FRIENDWS2_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(test.artefact.friends.FriendWS2_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = test.artefact.friends.FriendWS2_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080//PhasebookWSEJB/FriendWS2?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080//PhasebookWSEJB/FriendWS2?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FRIENDWS2_WSDL_LOCATION = url;
    }

    public FriendWS2_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FriendWS2_Service() {
        super(FRIENDWS2_WSDL_LOCATION, new QName("http://webservices2/", "FriendWS2"));
    }

    /**
     * 
     * @return
     *     returns FriendWS2
     */
    @WebEndpoint(name = "FriendWS2Port")
    public FriendWS2 getFriendWS2Port() {
        return super.getPort(new QName("http://webservices2/", "FriendWS2Port"), FriendWS2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FriendWS2
     */
    @WebEndpoint(name = "FriendWS2Port")
    public FriendWS2 getFriendWS2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices2/", "FriendWS2Port"), FriendWS2.class, features);
    }

}
