
package test.artefact.friends;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FriendWS2", targetNamespace = "http://webservices2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FriendWS2 {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFriend", targetNamespace = "http://webservices2/", className = "test.artefact.friends.AddFriend")
    @ResponseWrapper(localName = "addFriendResponse", targetNamespace = "http://webservices2/", className = "test.artefact.friends.AddFriendResponse")
    public String addFriend(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

}
