
package test.artefact.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UserWS2", targetNamespace = "http://webservices2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWS2 {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loginWS2", targetNamespace = "http://webservices2/", className = "test.artefact.user.LoginWS2")
    @ResponseWrapper(localName = "loginWS2Response", targetNamespace = "http://webservices2/", className = "test.artefact.user.LoginWS2Response")
    public String loginWS2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerWS2", targetNamespace = "http://webservices2/", className = "test.artefact.user.RegisterWS2")
    @ResponseWrapper(localName = "registerWS2Response", targetNamespace = "http://webservices2/", className = "test.artefact.user.RegisterWS2Response")
    public String registerWS2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://webservices2/", className = "test.artefact.user.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://webservices2/", className = "test.artefact.user.GetUserByIdResponse")
    public String getUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

}
