
package client.artefact.posts;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PostWS2Service", targetNamespace = "http://webservices2/", wsdlLocation = "http://localhost:25227/PhasebookWSEJB/PostWS2?wsdl")
public class PostWS2Service
    extends Service
{

    private final static URL POSTWS2SERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:25227/PhasebookWSEJB/PostWS2?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        POSTWS2SERVICE_WSDL_LOCATION = url;
    }

    public PostWS2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PostWS2Service() {
        super(POSTWS2SERVICE_WSDL_LOCATION, new QName("http://webservices2/", "PostWS2Service"));
    }

    /**
     * 
     * @return
     *     returns PostWS2
     */
    @WebEndpoint(name = "PostWS2Port")
    public PostWS2 getPostWS2Port() {
        return (PostWS2)super.getPort(new QName("http://webservices2/", "PostWS2Port"), PostWS2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostWS2
     */
//    @WebEndpoint(name = "PostWS2Port")
//    public PostWS2 getPostWS2Port(WebServiceFeature... features) {
//        return (PostWS2)super.getPort(new QName("http://webservices2/", "PostWS2Port"), PostWS2.class, features);
//    }

}
