
package client.artefact.friends;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FriendsWS2Service", targetNamespace = "http://webservices2/", wsdlLocation = "http://localhost:25227/PhasebookWSEJB/FriendsWS2?wsdl")
public class FriendsWS2Service
    extends Service
{

    private final static URL FRIENDSWS2SERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:25227/PhasebookWSEJB/FriendsWS2?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        FRIENDSWS2SERVICE_WSDL_LOCATION = url;
    }

    public FriendsWS2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FriendsWS2Service() {
        super(FRIENDSWS2SERVICE_WSDL_LOCATION, new QName("http://webservices2/", "FriendsWS2Service"));
    }

    /**
     * 
     * @return
     *     returns FriendsWS2
     */
    @WebEndpoint(name = "FriendsWS2Port")
    public FriendsWS2 getFriendsWS2Port() {
        return (FriendsWS2)super.getPort(new QName("http://webservices2/", "FriendsWS2Port"), FriendsWS2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FriendsWS2
     */
    @WebEndpoint(name = "FriendsWS2Port")
    public FriendsWS2 getFriendsWS2Port(WebServiceFeature... features) {
        return (FriendsWS2)super.getPort(new QName("http://webservices2/", "FriendsWS2Port"), FriendsWS2.class, features);
    }

}
