
package client.artefact.friends;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FriendsWS2", targetNamespace = "http://webservices2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FriendsWS2 {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFriendsByUserId", targetNamespace = "http://webservices2/", className = "client.artefact.friends.GetFriendsByUserId")
    @ResponseWrapper(localName = "getFriendsByUserIdResponse", targetNamespace = "http://webservices2/", className = "client.artefact.friends.GetFriendsByUserIdResponse")
    public String getFriendsByUserId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

}
